#!/bin/bash
# build.sh — Bundle mkramsys into a single distributable script
#
# Usage: ./build.sh [output]
#
# Embeds lib/*.sh, tools/cleansys.sh, and initramfs-tools/* into one file.
# Resource files are extracted to a temp directory at runtime.

set -e

ROOT=$(cd "$(dirname "$0")" && pwd)
OUT="${1:-dist/mkramsys}"

mkdir -p "$(dirname "$OUT")"

{
    # ── Header ────────────────────────────────────────────────────────────────

    cat <<HEADER
#!/bin/bash
# mkramsys — single-file bundle
# Generated by build.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Source: $(git -C "$ROOT" describe --always --dirty 2>/dev/null || echo unknown)
# Do not edit directly.

set -e
HEADER

    # ── Embedded resource files ───────────────────────────────────────────────

    for entry in \
        cleansys:tools/cleansys.sh \
        ramsys:initramfs-tools/scripts/ramsys \
        modules:initramfs-tools/modules
    do
        name="${entry%%:*}"
        path="${entry#*:}"
        echo
        echo "_embedded_${name}() {"
        echo "cat <<'_MKRAMSYS_EOF_'"
        cat "$ROOT/$path"
        echo "_MKRAMSYS_EOF_"
        echo "}"
    done

    # ── Resource extraction ───────────────────────────────────────────────────

    cat <<'BLOCK'

_RESOURCE_DIR=""

_extract_resources() {
    [ -n "$_RESOURCE_DIR" ] && return
    _RESOURCE_DIR=$(mktemp -d)
    mkdir -p "$_RESOURCE_DIR/tools" "$_RESOURCE_DIR/initramfs-tools/scripts"
    _embedded_cleansys > "$_RESOURCE_DIR/tools/cleansys.sh"
    chmod 755 "$_RESOURCE_DIR/tools/cleansys.sh"
    _embedded_ramsys > "$_RESOURCE_DIR/initramfs-tools/scripts/ramsys"
    _embedded_modules > "$_RESOURCE_DIR/initramfs-tools/modules"
}

_cleanup_resources() {
    [ -n "$_RESOURCE_DIR" ] && rm -rf "$_RESOURCE_DIR"
}
BLOCK

    # ── Shared library ────────────────────────────────────────────────────────

    echo
    tail -n +2 "$ROOT/lib/common.sh"

    # ── Subcommands ───────────────────────────────────────────────────────────
    # Inline lib/cmd_*.sh: rename cmd_run -> cmd_<name>_run,
    # replace LIBDIR-based scriptdir with $_RESOURCE_DIR.

    dispatch_cases=""
    for f in "$ROOT"/lib/cmd_*.sh; do
        cmd=$(basename "$f" .sh)
        cmd=${cmd#cmd_}
        echo
        tail -n +2 "$f" \
            | sed "s/^cmd_run/cmd_${cmd}_run/" \
            | sed 's|scriptdir="$(dirname "$(readlink -f "$LIBDIR")")".*|scriptdir="$_RESOURCE_DIR"|'
        dispatch_cases="${dispatch_cases}    ${cmd}) ( cmd_${cmd}_run \"\$@\" ) ;;\n"
    done

    # ── Dispatcher (from ./mkramsys) ──────────────────────────────────────────
    # Reuse usage + option parsing, strip LIBDIR and dynamic sourcing,
    # replace with resource extraction and static case dispatch.

    echo
    sed '/^LIBDIR=/d; /^# ── Source shared library/,$d' "$ROOT/mkramsys" \
        | tail -n +2

    # Static dispatch replaces the dynamic . "$LIBDIR/cmd_${COMMAND}.sh"
    printf '\n_extract_resources\ntrap _cleanup_resources EXIT\n\n'
    printf 'case "$COMMAND" in\n'
    printf "%b" "$dispatch_cases"
    printf '    *) echo "error: unknown command '\''$COMMAND'\''" >&2; usage 1 ;;\nesac\n'

} > "$OUT"

chmod +x "$OUT"

# Validate syntax
bash -n "$OUT"

echo "Built: $OUT ($(wc -c < "$OUT") bytes)"
